development: &defaults
  :vkontakte:
    :app_id: 5165818
    :app_secret: LnBQ95gE8SaBmqdY8AST
    :adapter: :Vkontakte
    :display: :popup    
  :facebook:
    :app_id: 529146080586779
    :app_secret: 9649102b146c53be71efabee5386625a
    :adapter: :Facebook
    :display: :popup
test:
  <<: *defaults

production:
  <<: *defaults
